spring.application.name=e-commerce

#Enable Swagger Ui
springdoc.api-docs.enable = true;
springdoc.swagger-ui.enable =  true;
springdoc.swagger-ui.path=/swagger-ui.html

#email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ajinkyabarkul368@gmail.com
spring.mail.password=qiml nipp zmum wlmt

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8


jwt.secret=pbv0iqiHxsauxotCxpyVDqcwyGMsU2aJwjq9LJgz90hB
jwt.expiration=7200000


#spring profile
spring.profiles.active =${PROFILE}